create table public.movement (
  id bigint generated by default as identity not null,
  product_id bigint null,
  type text null,
  quantity integer null,
  created_at timestamp with time zone not null default now(),
  constraint movement_pkey primary key (id),
  constraint movement_product_id_fkey foreign KEY (product_id) references product (id)
) TABLESPACE pg_default;