create table public.product (
  id bigint generated by default as identity not null,
  name text null,
  price integer null,
  current_stock,
  integer null,
  min_stock integer null,
  created_at timestamp with time zone not null default now(),
  constraint product_pkey primary key (id)
) TABLESPACE pg_default;